# File: .github/workflows/main.yml

name: CI_Eksperimen_SML_Mayang-Gumelar

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CSV_URL: "Eksperimen_SML_Mayang-Gumelar/preprocessing/Data_Liver_Cleaned.csv"
  TARGET_VAR: "Target"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout Repository
      uses: actions/checkout@v4

    - name: 2. Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Check Env (Debug)
      run: |
        echo "CSV Path: ${{ env.CSV_PATH }}"

    - name: 3. Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 4. Run Preprocessing Script
      run: |
        python Eksperimen_SML_Mayang-Gumelar/preprocessing/automate_Mayang-Gumelar.py

    - name: 5. Verify Output Files
      run: |
        echo "Verifying Preprocessing Outputs..."
        test -f Liver_train.csv
        test -f Liver_test.csv
        test -f RobustScaler.joblib
        
